### PR TITLE
Renew lgtx8p.h and lgtx8e.h with Arduino style register definitions.

### PR DESCRIPTION
**Pull request by LaZsolt**
`(*((volatile unsigned char *) address ))` replaced to `_SFR_MEM8( address )` or `_SFR_IO8( address )`
and replacement of the missing 16 bit registers definitions: `_SFR_MEM16( address )` or `_SFR_IO16( address )`
according to https://github.com/dbuezas/lgt8fx/issues/57#issue-718871897

### CODE REVIEW

**Comment by dbuezas** [comment]
Fantastic!
Please confirm you tested it by running code that uses some registers and I'll merge asap

**Comment by LaZsolt** [comment]
Not tested yet, but I read back every modification many times carefully. I ask others to help testing this two files.

**Comment by dbuezas** [comment]
Marked as draft, you can mark it as "not draft" when you've smoke tested it and want me to merge.
This looks so much better than before! 💯

**Comment by dbuezas** [comment]
By the way, related to register definitions, I use vscode and it is nice to get datasheet bits when you hover a register.
What do you think about [this](https://github.com/dbuezas/lgt8fx/blob/master/lgt8f/cores/lgt8f/lgtx8p_documentation.h) ?
Screen Shot 2021-02-14 at 21 21 03

**Comment by LaZsolt** [comment]
@dbuezas 
I think it is a lot of work to copy all resisters bits explanations from the databook to  this file. But at the end it will be look nice.

**Comment by LaZsolt** [comment]
Anyway, I have only one big project, based on LGT, which not using LGT's extra registers of related to timers. So I could test if the new files are free of compiler errors.

**Comment by dbuezas** [comment]
That should be enough for now, worse case scenario _some_ are not fully functional, which was already the case before.

**Comment by LaZsolt** [comment]
Tested with this program:
```
/* Timer3 overflow interrupt example for LGT8F328P microcontroller */

// LED_BUILTIN = D13

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);

// initialize Timer3
  noInterrupts();             // disable all interrupts
  TCCR3A = 0;
  TCCR3B = 0;
  TCCR3C = 0;
  TCCR3D = 0;

  TCNT3 = 49911;              // preload timer 65536-16MHz/1024/2Hz
  TCCR3B |= (1 << CS32) | (1 << CS30); // 1024 prescaler
  TIMSK3 |= (1 << TOIE3);     // enable timer overflow interrupt
  interrupts();               // enable all interrupts
}

ISR(TIMER3_vect) // interrupt service routine that wraps a user defined function supplied by attachInterrupt
{
  if (TIFR3 & (1 << TOIE3)) { // Examine which event happened
     TIFR3 = (1 << TOIE3);    // Clear Timer3 interrupt flag register by setting appropriate bit.
     TCNT3 = 49911;           // preload timer
     fastioToggle(D13);       // LED on D12 pin when using red Wemos XI TTGO board
  }
}

void loop() {
// nothing
}
```

**Comment by dbuezas** [comment]
Fantastic work @LaZsolt !
Merging now

**Pull request merged**
