### PR TITLE
Inadequate slash type in include path in lgt_lowpower library

### PR DESCRIPTION
**Pull request by LaZsolt**
According this issue ( https://github.com/LaZsolt/lgt8fx/issues/1 ) the include path has a windows type path separator which had to be corrected.

### CODE REVIEW

**Comment by dbuezas** [comment]
I see zero files changed, have you deleted them by accident?

**Comment by LaZsolt** [comment]
Hmmm. Strange. I modified 2 files.

**Comment by LaZsolt** [comment]
Now it's better.

**Comment by dbuezas** [comment]
Released

**Pull request merged**
