### PR TITLE
Pro Mini Style SSOP20 modification

### PR DESCRIPTION
**Pull request by LaZsolt**
Hi David!

New Pro Mini style boards equipped with LGT8F238P only. So I changed boards.txt Pro Mini SSOP20 sections to LGT8F328P support. After this modification Arduino IDE can properly compile LGT8F328P specific register and port names. But it wasn't enough. In ...\cores\lgt8f\main.cpp RXD, TXD, SS pins are redirected when SSOP20 compiled. Now for SS default Arduino pin is 9. It is important in my IOT application which using ENC28J60 ethernet module.

Best regards: Zsolt

### CODE REVIEW

**Comment by LaZsolt** [comment]
and added some documents

**Comment by LaZsolt** [comment]
Hi David!

I'm new in Github, so it is my first pull request. Accidentally closed it yesterday...

My modification:

New Pro Mini style boards equipped with LGT8F238P only. So I changed boards.txt Pro Mini SSOP20 sections to LGT8F328P support.

menu_SSOP20

After this modification Arduino IDE can properly compile LGT8F328P specific register and port names. But it wasn't enough for me. In this repository the ...\cores\lgt8f\main.cpp redirecting RXD, TXD, SS pins when SSOP20 compiled. The default SS Arduino pin must be defined to 9. 

 It is important in my IOT application which using ENC28J60 ethernet module.

Best regards: Zsolt

**Comment by dbuezas** [comment]
Hey @LaZsolt!, did you work further on this or is it in a finished state?
I finally got the time to make a new release :)

**Comment by LaZsolt** [comment]
It is a finished state.

**Comment by dbuezas** [comment]
As you noted, it's available in the new version. Thanks again for the contribution!

**Pull request merged**
