### PR TITLE
Improved accuracy in delayMicroseconds()

### PR DESCRIPTION
**Pull request by LaZsolt**
Improved accuracy in delayMicroseconds() and in clockCyclesToMicroseconds(),
more clock frequencies in delayMicroseconds(). ( 2, 4, 25, 32 MHz added)

### CODE REVIEW

**Comment by LaZsolt** [comment]
When I started to repair this code, I could not imagine that, it is not an easy task.

In the init() section, delayMicroseconds() must be initialized to avoid the optimization inside delayMiroseconds() function. Without this "if (us <= 1) return;" code not generated. (3/4 cycles)
````
void setup {
  delayMicroseconds(0);
}
````

Today I found a discussion about this, but the improvement never applied... https://github.com/arduino/ArduinoCore-avr/issues/118

**Comment by SuperUserNameMan** [comment]
@LaZsolt  :

I don't know if it could help you, but I've just discovered the existence of ``#pragma GCC optimize(...)`` which allows to selectively choose the optimization level to compile some parts of the code.

Typical usage i've seen so far is :
```
#pragma GCC push_options
#pragma GCC optimize("O3")
void foo()
{
 ...
}
#pragma GCC pop_options
```
Official doc : https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html

According to a GCC issue, it's not meant to work with the ``-fno-lto`` option ( see : https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61564 ), but maybe there are some gcc options that might solve your problem using this pragma ?

**Comment by LaZsolt** [comment]
@SuperUserNameMan 
Okay, but I seen somewhere a piece of code which select the different optimizaton options according version or type of the compiler.
I think must pay attention of this.

**Comment by LaZsolt** [comment]
I don't read all the pragmas, but it seems can not turn off LTO locally.
Must be referenced or  use somehow the "dead code". https://devblogs.microsoft.com/oldnewthing/20150102-00/?p=43233

**Comment by SuperUserNameMan** [comment]
@LaZsolt  : if calling ``delayMicroseconds(0);`` is your only solution, maybe you could just insert it into the ``main.cpp`` file ?

**Comment by dbuezas** [comment]
This can be merged right? If I understand the thread correctly, it is not perfect but still better than before, right?

**Comment by LaZsolt** [comment]
Yes, you are right. Better than before but if LTO is on, most of the case, 3 cycles shorter than calculated.
I think we can't reach better result in compatibile mode. So you can merge it, but I still working on.

**Comment by dbuezas** [comment]
I'm getting this error with this pr merged. Any ideas @LaZsolt ?
```
.....LGT8fx Boards/hardware/avr/1.0.6/cores/lgt8f/wiring.c:169:2: error: expected declaration or statement at end of input
  us -= 2; // = 1 cycle
  ^~
```

**Comment by LaZsolt** [comment]
I tried to compile to 32 MHz and 16 MHz but no error. Perhaps this line 1st char is not a space or tab? Or something wrong in previsous lines? On other frequencies, compile is good?

**Pull request merged**
