### PR TITLE
delayMicroseconds redesigned

### PR DESCRIPTION
**Pull request by LaZsolt**

### CODE REVIEW

**Comment by dbuezas** [comment]
Fantastic!

Another PR merge generated conflicts on this one.
Would you also add a line in the readme or a usage example?

**Comment by LaZsolt** [comment]
Readme and usage here:
https://github.com/dbuezas/lgt8fx/issues/18#issuecomment-770403353
and
https://github.com/LaZsolt/delayMicroseconds/tree/master/for_LGT8F

**Comment by LaZsolt** [comment]
Generally the usage of `delayMicroseconds()` not changed. The main difference is the lot of working frequency, clock tick accuracy and it's easy adaptable new code if needed.

**Comment by dbuezas** [comment]
Wow, fantastic. If you want, you can link to your pages in the readme.md or add an example file in the [libraries folder](https://github.com/dbuezas/lgt8fx/tree/master/lgt8f/libraries).
I'll merge this now since I see that it `just works` with the clock selected in the menu.
So much assembler wizardry!

**Comment by LaZsolt** [comment]
Okay, I'll write few lines.

**Pull request merged**
