### PR TITLE
add missing XCK definitions for USART SPI

### PR DESCRIPTION
**Pull request by jayzakk**
We are missing definitions for USART-as-SPI, which I was playing around with.

These are usually coming from avr-gcc mcu header files, but - as we know - in using the 328p files we are missing some functions and definitions ^^

I used the ones from iom324pa.h (as the most "identical" mcu) and changed accordingly.

### CODE REVIEW

**Comment by dbuezas** [comment]
You are really taking every bit ot this board apart! 🎉
Can you also put your code (your "playing around" sketch) in the examples folder?

**Comment by jayzakk** [comment]
At the moment, it got a rather "large" play code -> https://github.com/jayzakk/lgt8f-tests/blob/master/spitest-lgt8f/spitest-lgt8f.ino
Where I even did not need the XCK, as I just wanted to abuse the SPI for LEDs ^^ 

But I can build up some test code for whatever "real" SPI device I have around here,

**Comment by jayzakk** [comment]
@dbuezas, could we merge the two relevant files from https://github.com/jayzakk/spi-uart-test to core?

**Comment by dbuezas** [comment]
So this should be merged before?
https://github.com/dbuezas/lgt8fx/pull/45

**Comment by jayzakk** [comment]
If you merge, would be perfect, though it shows conflicts now

**Comment by dbuezas** [comment]
Can you fix them so I can merge this 🙏  :)

**Comment by dbuezas** [comment]
hey @jayzakk !
I'd love to merge this one, the conflict looks harmless, can you patch it? :)

**Comment by jayzakk** [comment]
Huh, I never used that web resolve thing. Guess it's ok now :-/

**Comment by LaZsolt** [comment]
@jayzakk  
> Huh, I never used that web resolve thing. Guess it's ok now :-/

Wasn't fully success that web resolve thing. I deleted that macros which was defined twice. https://github.com/dbuezas/lgt8fx/pull/122#issue-598056535

**Comment by jayzakk** [comment]
Thanks @LaZsolt 
I won't use that anymore ^^

**Pull request merged**
