### PR TITLE
Update to WDT library

### PR DESCRIPTION
**Pull request by gpb01**
Adds the capability of using the HFRC oscillator for WDT. A usage example has been added.

### CODE REVIEW

**Review by gpb01 — COMMENTED** [review]
Suggestions are always welcome. :-)

**Comment by LaZsolt** [comment]
I think it's fine.

**Comment by gpb01** [comment]
Yes 👍

You can merge the pull-request 😊

**Comment by dbuezas** [comment]
Thank you! 
What's the effect of using the other oscillator? Longer intervals?

**Comment by gpb01** [comment]
> What's the effect of using the other oscillator? Longer intervals?

The opposite, getting shorter intervals:

```
#define WTOH_1MS 0
#define WTOH_2MS 1
#define WTOH_4MS 2
#define WTOH_8MS 3
#define WTOH_16MS 4
#define WTOH_32MS 5
#define WTOH_64MS 6
#define WTOH_128MS 7
#define WTOH_256MS 8
#define WTOH_512MS 9
```

which can be useful on various occasions, e.g. either when the system clock is 32 MHz, or for porting libraries like FreeRTOS that use the WDT interrupt as a system tick.

Guglielmo

**Comment by gpb01** [comment]
PR is waiting ... :-)

Guglielmo

**Comment by dbuezas** [comment]
Oh no, sorry for making this wait!

**Comment by dbuezas** [comment]
Released https://github.com/dbuezas/lgt8fx/releases/tag/v2.0.7

**Pull request merged**
